# Generated by Django 3.1.4 on 2020-12-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_id', models.IntegerField()),
                ('logo_name', models.CharField(max_length=30)),
                ('logo_host', models.CharField(max_length=30)),
            ],
        ),
    ]
