# Generated by Django 3.1.4 on 2020-12-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo_host',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
