# Generated by Django 3.1.4 on 2020-12-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0002_auto_20201203_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo_host',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
